name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: '**/.github/workflows/*.yml'

      - name: Install dependencies
        run: npm install

      - name: Copy .env file
        run: cp .env.dist .env

      - name: Test all projects
        run: npm test -- --coverage

      - name: To Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}